In [20]:
import numpy as np

In [38]:
a=np.array([1,2,3],dtype="int8" )
print(a)

[1 2 3]


In [24]:
b=np.array([[9.0,8.0,7.0],[7.0,50.0,60.]])
print(b)

[[ 9.  8.  7.]
 [ 7. 50. 60.]]


In [25]:
#dimension
b.ndim

2

In [26]:
#shape
b.shape

(2, 3)

In [30]:
# get type
b.dtype
a.dtype

dtype('int16')

In [39]:
#get size
a.itemsize
b.itemsize

8

In [41]:
#get total size
a.nbytes

3