In [117]:
import numpy as np

In [118]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [119]:
#get a specific element [row,comma]
a[1,5]

13

In [120]:
#get specific row or column
a[:,1]

array([2, 9])

In [121]:
#[row,startindex:endindex:stepsize(multiples of)]
a[1,0:9:2]

array([ 8, 10, 12, 14])

In [122]:
#changing an element
#a[0,3]=2
#print(a)
a[:,2]=[1,3]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 13 14]]


In [123]:

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [124]:
#get specific element(work outside in) from outermost bracket to innermost
#b[0,1,1]
b[:,1,1]

array([4, 8])

In [125]:
#replace
#print(b)
#b[0,1,:]=[888,888]


In [126]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [127]:
#initializing different types of arrays


In [128]:
#all 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [129]:
#all 1's matrix
np.ones((4,2),dtype="int8")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [130]:
# any other number
np.full((2,3,3),2)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [131]:
#full_like passing in arrays which have been done earlier
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [132]:
#random decimal numbers 
np.random.rand(4,2)

array([[0.5584869 , 0.42517721],
       [0.20528985, 0.88492607],
       [0.69191992, 0.01534477],
       [0.5414612 , 0.39961993]])

In [133]:
#random integer values
np.random.randint(100,2000, size=(3,4))

array([[1869, 1847,  467,  368],
       [1168,  537, 1710,  359],
       [1951,  624, 1210, 1218]])

In [134]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [135]:
arr = np.array([[1,1,1,1,1],[1,0,0,0,1], [1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
r1 = np.repeat(arr, 1, axis=0)
print(r1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [187]:
output = np.ones((5,5))
#print(output)
z = np.zeros((3,3))
z[1,1]=9
#print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be careful while co

In [137]:
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


##### Mathematics

In [138]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [139]:
a+2

array([3, 4, 5, 6])

In [140]:
a-1

array([0, 1, 2, 3])

In [141]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [142]:
a*3

array([ 3,  6,  9, 12])

In [143]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [144]:
#sin of all values 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear algebra

In [145]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

## statistics

In [146]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
np.max(stats)

6

## reorganizing arrays

In [148]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [149]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [150]:
# horizontal stack
h1 = np.zeros((2,4))
h2 = np.full((2,4),2)
np.hstack([h1,h2])

array([[0., 0., 0., 0., 2., 2., 2., 2.],
       [0., 0., 0., 0., 2., 2., 2., 2.]])

# Miscellaneous
### Local data from file

In [172]:

filedata = np.genfromtxt("data.txt", delimiter=",")
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### boolean masking advanced indexing

In [183]:
(~(filedata>50) | (filedata<6))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])